#!/usr/bin/env ruby
# frozen_string_literal: true

require 'debug'

input = <<~TEST_INPUT
47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47
TEST_INPUT

input = IO.read('input.txt')
cut_index = input.index("\n\n")

rules_str = input[..cut_index].split
pages_str = input[cut_index..].split

rules = Hash.new { |hash, key| hash[key] = [] }

rules_str.each do |r|
  p1, p2 = r.split("|")

  rules[p1] << p2
end

invalids = []

pages_str.each do |pages|

  valid = true
  split_pages = pages.split(",")
  split_pages.each_with_index do |page, index|
    prev = split_pages[...index]

    unless (rules[page] & prev).empty?
      valid = false
      break
    end
  end

  invalids << split_pages unless valid
  # puts valid
  valid = true
end

mids = 0

puts rules

invalids.each do |pages|
  index = 0

  loop do
    # first element is always before everything
    index += 1

    page = pages[index]
    rule = rules[page]

    # test if any of the pages in the rules is before the current page
    (rule & pages).each do |rule_page|
      next unless pages[...index].include?(rule_page)

      # if rule has elements, this means his page should be before any of these
      # Let's try moving it before the first element that belongs to this list
      pages.delete(page)
      i = pages.index(rule_page)
      pages.insert(i, page)

      # restart
      index = 0
    end

    break if index >= pages.size
  end

  puts pages.join(",")
  mids += pages[pages.size/2].to_i
end

puts mids
