#!/usr/bin/env ruby
# frozen_string_literal: true

require 'debug'

Location = Struct.new(:x, :y)

class Guard
  LOOK_UP = '^'
  LOOK_DOWN = 'v'
  LOOK_RIGHT = '>'
  LOOK_LEFT = '<'
  DIRECTIONS = [LOOK_UP, LOOK_RIGHT, LOOK_DOWN, LOOK_LEFT].cycle

  attr_accessor :lab_map, :current_location, :visited_locations, :current_direction, :wall_added

  def initialize(lab_map:, start_location:, direction:)
    @current_location = start_location
    @current_direction = direction
    @lab_map = lab_map
    @visited_locations = [current_location.clone]
    @wall_added = false
  end

  def clone
    clone = super
    clone.current_location = current_location.clone
    clone.current_direction = current_direction.clone
    clone.lab_map = lab_map.map(&:clone)
    clone.visited_locations = visited_locations.clone
    clone
  end

  def move!
    lab_map[y][x] = 'X'

    case current_direction
    when LOOK_UP then current_location.y -= 1
    when LOOK_DOWN then current_location.y += 1
    when LOOK_LEFT then current_location.x -= 1
    when LOOK_RIGHT then current_location.x += 1
    end

    return if out?

    lab_map[y][x] = current_direction

    # puts current_location
    visited_locations << current_location.clone
  end

  def obstacle_ahead?
    case current_direction
    when LOOK_UP then lab_map.fetch(y - 1, [])[x] == '#'
    when LOOK_RIGHT then lab_map.fetch(y, [])[x + 1] == '#'
    when LOOK_DOWN then lab_map.fetch(y + 1, [])[x] == '#'
    when LOOK_LEFT then lab_map.fetch(y, [])[x - 1] == '#'
    end
  end

  def turn!
    self.current_direction = DIRECTIONS.next
    lab_map[y][x] = current_direction
    self.current_location = Location.new(x:, y:)
  end

  def out?(xi: x, yi: y)
    xi.negative? || xi >= lab_map[0].size || yi.negative? || yi >= lab_map.size
  end

  def x = current_location.x

  def y = current_location.y

  def loop_found? = visited_locations[...-1].include?(current_location)

  def surrounded?
    [[y - 1, x],
     [y, x + 1],
     [y + 1, x],
     [y, x - 1]].all? { |p| lab_map[p[0]][p[1]] == '#' }
  end

  def surrounding_locations = {
    LOOK_UP => Location.new(x: x, y: y - 1),
    LOOK_RIGHT => Location.new(x: x + 1, y: y),
    LOOK_DOWN => Location.new(x: x, y: y + 1),
    LOOK_LEFT => Location.new(x: x - 1, y: y)
  }

  def possible_walls
    surrounding_locations
      .reject { |k, _| k == current_direction }
      .reject { |_, v| out?(xi: v.x, yi: v.y) }
      .reject { |_, v| lab_map[v.y][v.x] == '#' }
      .map { |_, v| v }
  end

  def add_wall!(wall_pos)
    lab_map[wall_pos.y][wall_pos.x] = '#'
    self.wall_added = true
  end
end

def follow(guard:)
  if guard.loop_found?
    puts 'F'
    return
  end

  return if guard.out? || guard.surrounded?

  unless guard.wall_added
    guard.possible_walls.each do |wall_pos|
      guard_clone = guard.clone
      guard_clone.add_wall!(wall_pos)

      follow(guard: guard_clone)
    end
  end

  if guard.obstacle_ahead?
    guard.turn!
  else
    guard.move!
  end

  follow(guard:)
end

input = <<~TEST_INPUT
  ....#.....
  .........#
  ..........
  ..#.......
  .......#..
  ..........
  .#..^.....
  ........#.
  #.........
  ......#...
TEST_INPUT

# input = IO.read('input.txt')

start = input.delete("\n").index(Guard::LOOK_UP)
lab_map = input.split("\n").map(&:chars)
x = start % lab_map.size
y = start / lab_map[0].size

start_location = Location.new(x:, y:)
guard = Guard.new(lab_map:, start_location:, direction: Guard::LOOK_UP)
# debugger

follow(guard:)
# puts guard.lab_map.map{|m|m.join}
# puts "---------------"
# lab_map[0].size.times do|xi|
#   lab_map[0].size.times do|yi|
#     print guard.visited_locations.include?(Location.new(x: yi, y: xi)) ? 'X' : '.'
#   end
#   print "\n"
# end
# puts guard.visited_locations
#
#
#
