require 'minitest/autorun'
require 'minitest/pride'
require 'debug'
require_relative 'solution'

class Test < Minitest::Test
  def test_surrounded
    input = <<~TEST_INPUT
      ..........
      ..........
      ..........
      ..........
      ..........
      ....#.....
      ...#^#....
      ....#.....
      ..........
      ..........
    TEST_INPUT

    start = input.delete("\n").index(Guard::LOOK_UP)
    lab_map = input.split("\n").map(&:chars)
    x = start % lab_map.size
    y = start / lab_map[0].size

    guard = Guard.new(lab_map: lab_map.map(&:clone), x:, y:)

    refute guard.loop_found?
    assert guard.surrounded?
    assert guard.stuck?
  end

end
